import type { SiteSeedData } from "./types.js";

const productImage = (file: string) =>
  `/assets/images/product-img/beauty-product/${file}`;

const categoryImage = (file: string) => `/assets/images/catagory-img/${file}`;

export const beautySeedData: SiteSeedData = {
  label: "beauty",
  primaryCategorySlug: "skincare",
  primaryBrandSlug: "glow-lab",
  categories: [
    {
      name: "Skincare",
      slug: "skincare",
      image: categoryImage("cat-transp-img-01.webp"),
      status: "published",
    },
    {
      name: "Makeup",
      slug: "makeup",
      image: categoryImage("cat-transp-img-02.webp"),
      status: "published",
    },
    {
      name: "Fragrance",
      slug: "fragrance",
      image: categoryImage("cat-transp-img-03.webp"),
      status: "published",
    },
    {
      name: "Hair Care",
      slug: "hair-care",
      image: categoryImage("cat-transp-img-04.webp"),
      status: "published",
    },
  ],
  brands: [
    {
      name: "Glow Lab",
      slug: "glow-lab",
      website: "glowlab.com",
      initials: "GL",
      tileClass: "bg-brand-50 text-brand-600",
      visibility: "Featured",
      status: "published",
    },
    {
      name: "Pure Skin",
      slug: "pure-skin",
      website: "pureskin.com",
      initials: "PS",
      tileClass: "bg-success-50 text-success-600",
      visibility: "Standard",
      status: "published",
    },
  ],
  attributes: [
    {
      name: "Skin Type",
      slug: "skin-type",
      displayType: "Dropdown",
      description: "Recommended skin type for the product.",
      status: "published",
      values: ["Oily", "Dry", "Combination", "Sensitive"],
    },
    {
      name: "SPF Level",
      slug: "spf-level",
      displayType: "Dropdown",
      description: "Sun protection factor.",
      status: "published",
      values: ["15", "30", "50"],
    },
  ],
  products: [
    {
      name: "Hydrating Vitamin C Serum",
      slug: "hydrating-vitamin-c-serum",
      sku: "BS-SK-001",
      description:
        "Brightening daily serum with stable vitamin C for an even, radiant complexion.",
      price: 42,
      compareAtPrice: 52,
      stock: 120,
      status: "published",
      categorySlug: "skincare",
      brandSlug: "glow-lab",
      images: [productImage("beauty-product-st-01.webp")],
      attributes: { "skin-type": "Combination" },
    },
    {
      name: "SPF 50 Daily Moisturizer",
      slug: "spf-50-daily-moisturizer",
      sku: "BS-SK-002",
      description:
        "Lightweight moisturizer with broad-spectrum SPF 50 for everyday protection.",
      price: 36,
      stock: 8,
      status: "published",
      categorySlug: "skincare",
      brandSlug: "glow-lab",
      images: [productImage("beauty-product-st-02.webp")],
      attributes: { "skin-type": "Sensitive", "spf-level": "50" },
    },
    {
      name: "Rosewater Balancing Toner",
      slug: "rosewater-balancing-toner",
      sku: "BS-SK-003",
      description:
        "Alcohol-free toner that refreshes skin and restores natural balance.",
      price: 24,
      stock: 64,
      status: "published",
      categorySlug: "skincare",
      brandSlug: "pure-skin",
      images: [productImage("beauty-product-st-03.webp")],
      attributes: { "skin-type": "Dry" },
    },
    {
      name: "Overnight Repair Cream",
      slug: "overnight-repair-cream",
      sku: "BS-SK-004",
      description:
        "Rich night cream for deep hydration and barrier repair while you sleep.",
      price: 58,
      stock: 45,
      status: "draft",
      categorySlug: "skincare",
      brandSlug: "pure-skin",
      images: [productImage("beauty-product-st-04.webp")],
      attributes: { "skin-type": "Dry" },
    },
    {
      name: "Matte Lip Color",
      slug: "matte-lip-color",
      sku: "BS-MK-001",
      description:
        "Long-wear matte lipstick with a comfortable, non-drying finish.",
      price: 22,
      compareAtPrice: 28,
      stock: 90,
      status: "published",
      categorySlug: "makeup",
      brandSlug: "glow-lab",
      images: [productImage("beauty-product-st-05.webp")],
    },
    {
      name: "Luminous Foundation",
      slug: "luminous-foundation",
      sku: "BS-MK-002",
      description:
        "Buildable medium coverage foundation with a natural luminous finish.",
      price: 34,
      stock: 55,
      status: "published",
      categorySlug: "makeup",
      brandSlug: "pure-skin",
      images: [productImage("beauty-product-st-06.webp")],
      attributes: { "skin-type": "Combination" },
    },
    {
      name: "Nude Eyeshadow Palette",
      slug: "nude-eyeshadow-palette",
      sku: "BS-MK-003",
      description:
        "Twelve versatile nude shades for everyday looks and soft evening glam.",
      price: 48,
      stock: 32,
      status: "published",
      categorySlug: "makeup",
      brandSlug: "glow-lab",
      images: [productImage("beauty-product-st-07.webp")],
    },
    {
      name: "Rose Eau de Parfum",
      slug: "rose-eau-de-parfum",
      sku: "BS-FR-001",
      description: "Floral fragrance with notes of rose, peony, and warm musk.",
      price: 72,
      compareAtPrice: 89,
      stock: 40,
      status: "published",
      categorySlug: "fragrance",
      brandSlug: "pure-skin",
      images: [productImage("beauty-product-st-08.webp")],
    },
    {
      name: "Citrus Body Mist",
      slug: "citrus-body-mist",
      sku: "BS-FR-002",
      description:
        "Light, refreshing body mist with bergamot and neroli for daily wear.",
      price: 28,
      stock: 75,
      status: "published",
      categorySlug: "fragrance",
      brandSlug: "glow-lab",
      images: [productImage("beauty-product-st-09.webp")],
    },
    {
      name: "Repairing Hair Mask",
      slug: "repairing-hair-mask",
      sku: "BS-HC-001",
      description:
        "Weekly treatment mask that restores shine and reduces breakage.",
      price: 32,
      stock: 48,
      status: "published",
      categorySlug: "hair-care",
      brandSlug: "pure-skin",
      images: [productImage("beauty-product-st-10.webp")],
    },
    {
      name: "Volumizing Shampoo",
      slug: "volumizing-shampoo",
      sku: "BS-HC-002",
      description:
        "Gentle sulfate-free shampoo that adds body without weighing hair down.",
      price: 18,
      stock: 110,
      status: "published",
      categorySlug: "hair-care",
      brandSlug: "glow-lab",
      images: [productImage("beauty-product-st-11.webp")],
    },
  ],
};
